import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigatorBar } from "@/components/navigator-bar";

export const metadata: Metadata = {
  title: "image-client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavigatorBar />
          <main className="flex-1 w-full px-4 py-6">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
